### ISSUE TITLE
sgx.py do not handle sys.exit(1) error during checks in skale-api

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/sgx.py#174]
With new SGX ZMQ check in watchdog we now have an error when only ZMQ port is closed on node. Error in sgx.py is not handled and whole check is failing

Port is closed via iptabes, telnet to sgx port 1026 is working, telnet to port 1031 is not

`skale-admin`: 2.8.0-beta.1

Logs: 
```
[2024-10-29 16:20:56,782] 3778 INFO /api/v1/health/sgx helper: Checking if skale-admin inited ...
[2024-10-29 16:20:56,783] 3778 INFO /api/v1/health/sgx filelock: Lock 140665565611536 acquired on /skale_node_data/init.lock
[2024-10-29 16:20:56,784] 3778 INFO /api/v1/health/sgx helper: Skale admin inited
[2024-10-29 16:20:56,785] 3778 INFO /api/v1/health/sgx filelock: Lock 140665565611536 released on /skale_node_data/init.lock
[2024-10-29 16:20:56,806] 3778 INFO /api/v1/health/sgx app: Processing request 9db1e703ee
[2024-10-29 16:35:19 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:3775)
[2024-10-29 16:35:19,195] 3775 INFO /api/v1/health/sgx app: Request finished 09e5fbc657, time elapsed: 1000s
[2024-10-29 16:35:19 +0000] [3775] [ERROR] Error handling request /api/v1/health/sgx
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/admin/web/routes/health.py", line 136, in sgx_info
    if sgx.zmq.get_server_status() == 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sgx/sgx_zmq.py", line 160, in get_server_status
    response = self.__send_request("getServerStatus")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sgx/sgx_zmq.py", line 281, in __send_request
    response_str = socket.recv().decode()
                   ^^^^^^^^^^^^^
  File "zmq/backend/cython/socket.pyx", line 805, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 841, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-10-29 16:35:19 +0000] [3775] [INFO] Worker exiting (pid: 3775)
[2024-10-29 16:35:19 +0000] [3786] [INFO] Booting worker with pid: 3786
```

**Comment by OleksanderSalamatov** [comment]
Verified

skale-admin: `2.8.0-beta.2`

Logs:
```
{"data": {"status_zmq": false, "status_https": true, "sgx_wallet_version": "1.9.0"}, "error": null}
```
